Post and delete gifs
aiyus2020/teamwork-backend pull request #3
Opened 2023-07-30 12:02 UTC by aiyus2020

2023-08-07 16:33 UTC, courage173 requested changes
please use migration file not sql!! you deleted the migration file

2023-08-07 16:33 UTC, courage173 commented on controllers/gifsController.js
> +      console.error("Error:", error.message);
remove console

2023-08-07 16:33 UTC, courage173 commented on controllers/userController.js
> +      // Validate the email format
please use a validator middleware to validate e.g joi validator, validatorJs

2023-08-07 17:15 UTC, aiyus2020 commented on controllers/gifsController.js
> +      console.error("Error:", error.message);
I don't delete the migration file, sir, it's in the model folder.❤

2023-08-07 17:16 UTC, aiyus2020 commented on controllers/userController.js
> +      // Validate the email format
ok sir

2023-08-12 21:05 UTC, courage173 requested changes

2023-08-12 21:05 UTC, courage173 commented on controllers/userController.js
> +      const schema = Joi.object({
your validation should be a middleware. you do not do this on the controller level

2023-08-12 21:05 UTC, courage173 commented on middleware/authmiddleware.js
> +module.exports = function authenticate(req, res, next) {
sorry i missed this earlier, what you need to do in this middleware is as follows
1. decode the token and get user id
2. get all user information from db using the id
3. append the fetched user from the db to the req.user e.g req.user = user(fetched from db)

In this way you will have the full user detail available to you in the controller.

2023-08-13 08:20 UTC, aiyus2020 commented on controllers/gifsController.js
> +      const user_id = req.user;
noted sir❤❤

2023-08-13 08:24 UTC, aiyus2020 commented on controllers/gifsController.js
> +      const public_id = result.public_id;
noted sire❤

2023-08-13 08:26 UTC, aiyus2020 commented on controllers/userController.js
> +      const schema = Joi.object({
noted sire❤

2023-08-13 15:52 UTC, aiyus2020 commented on middleware/authmiddleware.js
> +module.exports = function authenticate(req, res, next) {
done!❤

2023-08-14 20:05 UTC, courage173 requested changes
Almost there! just some small comments

2023-08-14 20:05 UTC, courage173 commented on middleware/userValidationMiddleware.js
> +const userSchema = Joi.object({
create a folder called model and add this userSchema there, then you import it to the file where you want to use it. in that way you can rename this file to just validation so that you can use the validateMiddleware in other controllers

2023-08-14 20:05 UTC, courage173 commented on controllers/gifsController.js
> +        upload_preset: "gifs",
change this to pictures. i know its gif and you can leave the naming as such but change to also save pictures as well

2023-08-15 09:10 UTC, aiyus2020 commented on middleware/userValidationMiddleware.js
> +const userSchema = Joi.object({
ok sire.❤

2023-08-16 06:46 UTC, courage173 approved these changes

2023-08-16 09:33 UTC, merged