Post edit delete articles
aiyus2020/teamwork-backend pull request #4
Opened 2023-08-19 17:29 UTC by aiyus2020

2023-08-28 08:20 UTC, courage173 requested changes

2023-08-28 08:20 UTC, courage173 commented on controllers/postArticleController.js
> +      const userId = req.user;
this is still wrong. i thought I asked you to correct this. it should be req.user.id, you should always append the full user object to the req.user inside the auth middleware

2023-08-28 08:20 UTC, courage173 commented on models/dbMigration.js
> +    console.log("Connected");
console

2023-08-28 11:25 UTC, aiyus2020 commented on controllers/postArticleController.js
> +      const userId = req.user;
noted sir❤

2023-08-28 11:26 UTC, aiyus2020 commented on models/dbMigration.js
> +    console.log("Connected");
noted

2023-08-29 19:49 UTC, courage173 commented on models/db.sql
> +        user_id INTEGER NOT NULL REFERENCES user(id),
it should be users

2023-08-30 06:15 UTC, aiyus2020 commented on models/db.sql
> +        user_id INTEGER NOT NULL REFERENCES user(id),
done

2023-09-01 10:02 UTC, courage173 approved these changes
Looks good

2023-09-01 11:19 UTC, merged