Gif article comment
aiyus2020/teamwork-backend pull request #5
Opened 2023-09-04 15:58 UTC by aiyus2020

2023-09-13 09:54 UTC, courage173 requested changes

2023-09-13 09:54 UTC, courage173 commented on controllers/commentController.js
> +      const getGifTitle = await client.query(findId, [id]);
no, there is no point adding this to what you are returning. please remove it

2023-09-13 09:54 UTC, courage173 commented on controllers/commentController.js
> +          message: "comment successfully created",
the message should not be inside the data, you should just return the created comment

2023-09-13 09:54 UTC, courage173 commented on controllers/commentController.js
> +      const getArticle = await client.query(findArticleId, [id]);
same with this

2023-09-13 09:54 UTC, courage173 commented on controllers/gifsController.js
> +          upload: upload.rows[0].cloud_public_id,
why should you add this after deleting?? the message is enough

2023-09-13 09:54 UTC, courage173 commented on models/dbMigration.js
> +    const articleComment = `CREATE TABLE IF NOT EXISTS article_comments (
if you have this why do you still need the db sql

2023-09-13 09:54 UTC, courage173 commented on queries/commentQuery.js
> +const findArticleId = "SELECT * FROM articles WHERE id=$1";
this should be findArticleById

2023-09-13 10:30 UTC, aiyus2020 commented on controllers/commentController.js
> +      const getGifTitle = await client.query(findId, [id]);
<img width="466" alt="gifs" src="https://github.com/aiyus2020/teamwork-backend/assets/120171375/623a598d-1225-4744-8dbb-644990b54db5">

I did it to assess the gifs title in the upload gifs table,
so I can return it in the response.

2023-09-13 10:32 UTC, aiyus2020 commented on controllers/commentController.js
> +          message: "comment successfully created",
<img width="466" alt="gifs" src="https://github.com/aiyus2020/teamwork-backend/assets/120171375/5f19f6cb-f82e-4faa-8886-17408983f569">
The message was returned in the template shown above

2023-09-13 10:34 UTC, aiyus2020 commented on controllers/commentController.js
> +      const getArticle = await client.query(findArticleId, [id]);
<img width="479" alt="art" src="https://github.com/aiyus2020/teamwork-backend/assets/120171375/56ba2062-b44a-49e9-86f5-96383496e3e4">

I did it to assess the article title in the article table,
so I can return it in the response.

2023-09-13 10:42 UTC, aiyus2020 commented on models/dbMigration.js
> +    const articleComment = `CREATE TABLE IF NOT EXISTS article_comments (
I don't really need it, was just writing it initially to practice SQL. will delete it now

2023-09-13 10:44 UTC, aiyus2020 commented on queries/commentQuery.js
> +const findArticleId = "SELECT * FROM articles WHERE id=$1";
noted, and correction was effected accordingly. sir

2023-09-13 13:44 UTC, courage173 commented on controllers/commentController.js
> +      const getGifTitle = await client.query(findId, [id]);
okay. but please remove it. no point making that extra call

2023-09-13 13:55 UTC, aiyus2020 commented on controllers/commentController.js
> +      const getGifTitle = await client.query(findId, [id]);
noted sire.

2023-09-15 08:38 UTC, courage173 requested changes

2023-09-15 12:03 UTC, aiyus2020 commented on routes/commentRoute.js
> +router.post(
Added validation for articles, article comments and gif comments respectively sir. 👌

2023-09-16 10:16 UTC, courage173 requested changes
please remove that code you added and you can merge

2023-09-16 10:16 UTC, courage173 commented on controllers/commentController.js
> +      if (myGifComment.rows.comment.le == 0) {
what is this please?

2023-09-16 10:32 UTC, aiyus2020 commented on controllers/commentController.js
> +      if (myGifComment.rows.comment.le == 0) {
it was a mistake.
will remove it

2023-09-16 10:49 UTC, merged