Get gifsa articles
aiyus2020/teamwork-backend pull request #6
Opened 2023-10-17 14:12 UTC by aiyus2020

2023-10-29 13:22 UTC, courage173 requested changes

2023-10-29 13:22 UTC, courage173 commented on controllers/getArtGifController.js
> +      const { gif_id } = req.params;
this should be camel case

2023-10-29 13:22 UTC, courage173 commented on controllers/getArtGifController.js
> +      res.json({
this is wrong. you should write a query to fetch gifs and for each return 3 comments each.

2023-10-29 13:22 UTC, courage173 commented on queries/getArtGifQuery.js
> +  "SELECT g.gifs_id AS gif_id, c.gif_id AS comment_id, u.id, g.title, g.image_url,  c.comment AS gif_comment, g.created_at FROM upload g LEFT JOIN gif_comments c ON g.gifs_id = c.gif_id LEFT JOIN use
you have to use a subquery to select the comment so you can limit to 3 and also pass the limit as a parameter with a default of 3

2023-10-30 07:11 UTC, aiyus2020 commented on controllers/getArtGifController.js
> +      const { gif_id } = req.params;
done

2023-10-30 08:42 UTC, aiyus2020 commented on controllers/getArtGifController.js
> +      res.json({
done

2023-10-30 08:43 UTC, aiyus2020 commented on queries/getArtGifQuery.js
> +  "SELECT g.gifs_id AS gif_id, c.gif_id AS comment_id, u.id, g.title, g.image_url,  c.comment AS gif_comment, g.created_at FROM upload g LEFT JOIN gif_comments c ON g.gifs_id = c.gif_id LEFT JOIN use
done

2023-11-05 20:45 UTC, courage173 approved these changes

2023-11-07 01:07 UTC, merged